### ISSUE TITLE
cannot get this plugin to work

### ISSUE THREAD

**Issue by dgiffen** [abba23/beets-popularity#2]
I installed this on a Mint18 box and it will not work. I also tried on a ubuntu server and got the same errors. 
beets version 1.4.5
Python version 3.5.2
plugins: acousticbrainz, chroma, convert, discogs, embedart, fetchart, follow, ftintitle, inline, lastgenre, popularity, replaygain, rewrite, scrub

ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python3.5/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.5/dist-packages/beetsplug/popularity.py", line 43, in _command
    self._set_popularity(item, opts.nowrite)
  File "/usr/local/lib/python3.5/dist-packages/beetsplug/popularity.py", line 62, in _set_popularity
    response_json = json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by abba23** [comment]
I'm not sure why that is happening for you. It's working fine for me with Python 3.6.2.

Anyway, I just pushed a change (1177a40763bb7218fe9622e7a077020fb70eacb0) to explicitly treat the server response as text. Can you pull the change and see if that fixes it for you?

**Comment by dgiffen** [comment]
Will do. Later today. I had some similar issues with the chroma plug in.
Adrian fixed it for the most part. No worries for me, I appreciate all the
effort that you put in to this. I also appreciate the fast response.

Thanks
Doug

**Comment by dgiffen** [comment]
I would appear you fix corrected the issue. Working now. Will let you know
if I run into any other errors. Thank you so much

Thanks again
Doug

**Comment by dgiffen** [comment]
This is working great. Not sure here if this is an age related thing, but I
am 66 and so I really like 60' and 70's stuff. That stuff seems to score
fairly low, 30 more or less. I am wondering if there is a method to add
personal scores in. Say something I like only gets a 25, but I want to make
it 70 to appear in a smart list.

Thanks so much for helping me, it is really appreciated
Doug

**Comment by abba23** [comment]
The popularity values are stored as flexible attributes in the beets database. You can use beet's `modify` command ([documentation](https://beets.readthedocs.io/en/v1.4.5/reference/cli.html#modify)) to change them.

An example would be:
`beet modify "bee gees stayin alive" popularity=70`

**Comment by dgiffen** [comment]
Perfect. You are the best.

Thanks
Doug
