### ISSUE TITLE
unable to execute "beet popularity"

### ISSUE THREAD

**Issue by jones1008** [abba23/beets-popularity#3]
I recently tried to install beets-popularity with the command:
`pip3 install beets-popularity`
which gave me some "bdist_wheel" errrors, but ran through and and at the end it said:
> Successfully installed beets-popularity [...]

I then uninstalled the package and some dependencies with `pip-autoremoveautoremove beets-popularity` which uninstalled the following:
> munkres 1.0.12
> jellyfish 0.5.6
> PyYAML 3.12
> musicbrainzngs 0.6

I then uninstalled all the other dependencies except beets itself

Then I installed the python wheel package with `pip3 install wheel` which was obviously missing (see bdist_wheel error above)
After that the installation of beets-popularity went through well but I could not execute
`beet popularity` because it says
> error: unknown command 'popularity'

Installing it via the `python3 setup.py install` command goes through without error too...

What am I doing wrong?

Note: I am a noob about python and pip...

**Comment by abba23** [comment]
Just to be sure, did you add it to your config file [as described in the documentation](https://beets.readthedocs.io/en/latest/plugins/index.html#using-plugins)? Maybe I should add that to the installation instructions.

**Comment by jones1008** [comment]
Yeah, I feel so dumb now...
I forgot to add 'popularity' to the plugins section within the beets config.
But actually there is no word about adding 'popularity' to the plugins section... Maybe it would be useful to add that information to the installation instructions.

Thanks for the hint though! and for the awesome software! 👍

**Comment by abba23** [comment]
You're welcome! I added a hint to the installation instructions (https://github.com/abba23/beets-popularity/commit/4cf06512af0e20200b667aaff3128fe6da87a53d), so that nobody will forget about enabling it in the future.
