### ISSUE TITLE
can't find popularity when item is a singleton

### ISSUE THREAD

**Issue by jones1008** [abba23/beets-popularity#4]
When an item is imported as a singleton beets-popularity won't be able to retrieve the popularity because it searches the api [also with the album tag](https://github.com/abba23/beets-popularity/blob/master/beetsplug/popularity.py#L51). And since the album tag of singletons is null or takes the value from what was it before (for me it's the value "Singles") it won't find anything on Deezer.

Could you please remove the album variable when searching for popularity for a singleton?

Or even better:
you could add a switch (maybe configurable in the beets config.yaml) that decides whether to
1. always use albums in the request
2. generally don't use the album tag in the request
3. only use the album tag in request for non-singletons (tracks with albums)

**Comment by jones1008** [comment]
I just noticed that when you leave away the album tag with the request it is logically more presumable that it wont be the [first match](https://github.com/abba23/beets-popularity/blob/master/beetsplug/popularity.py#L70) in the answer.
You may have to iterate through the received results and compare title and artist that was sent with the title and artist that gave the result...

**Comment by jones1008** [comment]
I changed popularity.py by myself temporarily so it works for me now!
For those who are curious, I [copied it to a gist](https://gist.github.com/jones1008/fdb746271086c2ec4b800d99f401df2d)

@abba23 if you want you can close this issue, since it is resolved for me. But if you want to improve your software you should leave it open and implement it better than my temporary solution (see in the gist)...

**Comment by abba23** [comment]
> Could you please remove the album variable when searching for popularity for a singleton?

I agree, that would make sense.

>you could add a switch (maybe configurable in the beets config.yaml)

I don't think that's neccessary. It's really only useful to ignore the album property when it isn't available. In all other cases it would just worsen the search results.

>You may have to iterate through the received results and compare title and artist that was sent with the title and artist that gave the result...

Thanks for the hint. I'll have to look at that.

>if you want you can close this issue, since it is resolved for me. But if you want to improve your software you should leave it open and 
implement it better than my temporary solution (see in the gist)...

I don't have the time at the moment, but this is definitely something I plan on fixing. Feel free to create a pull request though if you want ;)

**Comment by jones1008** [comment]
I had a closer look at how the API behaves with some different querys.
And I created a [pull request](https://github.com/abba23/beets-popularity/pull/5) too
